
-- 1. Pastikan tabel ada
CREATE TABLE IF NOT EXISTS public.site_settings (
  id bigint PRIMARY KEY
);

-- 2. Tambahkan kolom snake_case (Target Standar)
ALTER TABLE public.site_settings 
ADD COLUMN IF NOT EXISTS hero_title text,
ADD COLUMN IF NOT EXISTS hero_subtitle text,
ADD COLUMN IF NOT EXISTS about_image text,
ADD COLUMN IF NOT EXISTS founder_portrait text,
ADD COLUMN IF NOT EXISTS sibos_url text,
ADD COLUMN IF NOT EXISTS qalam_url text,
ADD COLUMN IF NOT EXISTS dapur_sppg_url text,
ADD COLUMN IF NOT EXISTS company_legal_name text,
ADD COLUMN IF NOT EXISTS nib_number text,
ADD COLUMN IF NOT EXISTS ahu_number text,
ADD COLUMN IF NOT EXISTS npwp_number text,
ADD COLUMN IF NOT EXISTS whatsapp_number text,
ADD COLUMN IF NOT EXISTS email_address text,
ADD COLUMN IF NOT EXISTS address_solo text,
ADD COLUMN IF NOT EXISTS address_blora text,
ADD COLUMN IF NOT EXISTS map_solo_link text,
ADD COLUMN IF NOT EXISTS map_blora_link text,
ADD COLUMN IF NOT EXISTS map_solo_embed text,
ADD COLUMN IF NOT EXISTS map_blora_embed text,
ADD COLUMN IF NOT EXISTS instagram_url text,
ADD COLUMN IF NOT EXISTS facebook_url text,
ADD COLUMN IF NOT EXISTS youtube_url text,
ADD COLUMN IF NOT EXISTS tiktok_url text,
ADD COLUMN IF NOT EXISTS linkedin_url text,
ADD COLUMN IF NOT EXISTS google_analytics_id text,
ADD COLUMN IF NOT EXISTS google_search_console_code text,
ADD COLUMN IF NOT EXISTS google_merchant_id text,
ADD COLUMN IF NOT EXISTS timezone text,
ADD COLUMN IF NOT EXISTS quota_onsite_max int DEFAULT 5,
ADD COLUMN IF NOT EXISTS quota_onsite_used int DEFAULT 0,
ADD COLUMN IF NOT EXISTS quota_digital_max int DEFAULT 3,
ADD COLUMN IF NOT EXISTS quota_digital_used int DEFAULT 0;

-- 3. Masukkan Data (Upsert ID 1)
INSERT INTO public.site_settings (
  id,
  hero_title, hero_subtitle, 
  about_image, founder_portrait,
  sibos_url, qalam_url, dapur_sppg_url,
  company_legal_name, nib_number, ahu_number, npwp_number,
  whatsapp_number, email_address,
  address_solo, address_blora,
  map_solo_link, map_blora_link,
  map_solo_embed, map_blora_embed,
  instagram_url, facebook_url, youtube_url, tiktok_url, linkedin_url,
  google_analytics_id, google_search_console_code, google_merchant_id,
  timezone,
  quota_onsite_max, quota_onsite_used, quota_digital_max, quota_digital_used
) VALUES (
  1,
  'MESIN KASIR SOLO', 'Pusat penjualan mesin kasir (POS) dan jasa arsitek sistem digital untuk UMKM.',
  'https://res.cloudinary.com/doulbr8yn/image/upload/v1767621621/xn533gkhdnjddup5af14.jpg', 'https://res.cloudinary.com/doulbr8yn/image/upload/v1767621625/gjakrunbyhdhtvpfxoda.jpg',
  'https://web-sibos.vercel.app/', 'https://qalam-website.vercel.app/', 'https://dapursppg.id',
  'PT MESIN KASIR SOLO', '1226000711085', 'AHU-006097.AH.01.30.Tahun 2021', '53.494.885.6-532.000',
  '628816566935', 'owner.kasirsolo@gmail.com',
  'Perum Graha Tiara 2 B1, Gumpang 07/01, Kartasura, Sukoharjo, Jawa Tengah, Indonesia 57169', 'Gumiring 04/04, Sidomulyo, Banjarejo, Blora, Jawa Tengah, Indonesia 58253',
  'https://maps.app.goo.gl/JJdTYfDNhwamLg3k7', 'https://maps.app.goo.gl/n73NrHmTmK9ksBrA7',
  '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3955.0583936097605!2d110.7507075750027!3d-7.568613092445459!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e7a1531287b240f%3A0x4bbeeafd3bf04651!2sPerum%20Graha%20Tiara%202!5e0!3m2!1sid!2sid!4v1767605025124!5m2!1sid!2sid" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>', '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3959.789332509328!2d111.38257547579018!3d-7.034029468917307!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e77432e83d3b0fb%3A0x4cc1006079eb6653!2sMasjid%20Lama%20Roudlotul%20Jannah!5e0!3m2!1sid!2sid!4v1767605054365!5m2!1sid!2sid" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>',
  'https://instagram.com/', 'https://facebook.com/', 'https://youtube.com/', 'https://tiktok.com/', 'https://linkedin.com/',
  'G-YW8R9D4CX1', 'BxyqIpf1OTcFQVtRHhklXTUuH-oZyCdHDvmqJ0d0LsE', '',
  'Asia/Jakarta',
  5, 2, 3, 1
)
ON CONFLICT (id) DO UPDATE SET
  hero_title = EXCLUDED.hero_title,
  hero_subtitle = EXCLUDED.hero_subtitle,
  about_image = EXCLUDED.about_image,
  founder_portrait = EXCLUDED.founder_portrait,
  sibos_url = EXCLUDED.sibos_url,
  qalam_url = EXCLUDED.qalam_url,
  dapur_sppg_url = EXCLUDED.dapur_sppg_url,
  company_legal_name = EXCLUDED.company_legal_name,
  nib_number = EXCLUDED.nib_number,
  ahu_number = EXCLUDED.ahu_number,
  npwp_number = EXCLUDED.npwp_number,
  whatsapp_number = EXCLUDED.whatsapp_number,
  email_address = EXCLUDED.email_address,
  address_solo = EXCLUDED.address_solo,
  address_blora = EXCLUDED.address_blora,
  map_solo_link = EXCLUDED.map_solo_link,
  map_blora_link = EXCLUDED.map_blora_link,
  map_solo_embed = EXCLUDED.map_solo_embed,
  map_blora_embed = EXCLUDED.map_blora_embed,
  instagram_url = EXCLUDED.instagram_url,
  facebook_url = EXCLUDED.facebook_url,
  youtube_url = EXCLUDED.youtube_url,
  tiktok_url = EXCLUDED.tiktok_url,
  linkedin_url = EXCLUDED.linkedin_url,
  google_analytics_id = EXCLUDED.google_analytics_id,
  google_search_console_code = EXCLUDED.google_search_console_code,
  google_merchant_id = EXCLUDED.google_merchant_id,
  timezone = EXCLUDED.timezone,
  quota_onsite_max = EXCLUDED.quota_onsite_max,
  quota_onsite_used = EXCLUDED.quota_onsite_used,
  quota_digital_max = EXCLUDED.quota_digital_max,
  quota_digital_used = EXCLUDED.quota_digital_used;

-- 4. Bersihkan kolom CamelCase (OPTIONAL - Tapi disarankan agar rapi)
ALTER TABLE public.site_settings 
DROP COLUMN IF EXISTS "heroTitle",
DROP COLUMN IF EXISTS "heroSubtitle",
DROP COLUMN IF EXISTS "aboutImage",
DROP COLUMN IF EXISTS "founderPortrait",
DROP COLUMN IF EXISTS "sibosUrl",
DROP COLUMN IF EXISTS "qalamUrl",
DROP COLUMN IF EXISTS "dapurSppgUrl",
DROP COLUMN IF EXISTS "dapursppgurl",
DROP COLUMN IF EXISTS "companyLegalName",
DROP COLUMN IF EXISTS "nibNumber",
DROP COLUMN IF EXISTS "ahuNumber",
DROP COLUMN IF EXISTS "npwpNumber",
DROP COLUMN IF EXISTS "whatsappNumber",
DROP COLUMN IF EXISTS "emailAddress",
DROP COLUMN IF EXISTS "addressSolo",
DROP COLUMN IF EXISTS "addressBlora",
DROP COLUMN IF EXISTS "mapSoloLink",
DROP COLUMN IF EXISTS "mapBloraLink",
DROP COLUMN IF EXISTS "mapSoloEmbed",
DROP COLUMN IF EXISTS "mapBloraEmbed",
DROP COLUMN IF EXISTS "instagramUrl",
DROP COLUMN IF EXISTS "facebookUrl",
DROP COLUMN IF EXISTS "youtubeUrl",
DROP COLUMN IF EXISTS "tiktokUrl",
DROP COLUMN IF EXISTS "linkedinUrl",
DROP COLUMN IF EXISTS "googleAnalyticsId",
DROP COLUMN IF EXISTS "googleSearchConsoleCode",
DROP COLUMN IF EXISTS "quotaOnsiteMax",
DROP COLUMN IF EXISTS "quotaOnsiteUsed",
DROP COLUMN IF EXISTS "quotaDigitalMax",
DROP COLUMN IF EXISTS "quotaDigitalUsed";
